apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: broadcaster-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Asadullah378/DevOps-With-Kubernetes
    path: Broadcaster/manifests/overlays/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

